title:				Bunker Literário
tagline: 			'liberdade literária & fan fiction'
description: 		'Blog de divulgação do ideal de liberdade literária e Fan Fiction - Leia nosso Manifesto'
url:				http://bunkerliterario.github.io

permalink: pretty

author:
  name:			'Andre Santos'
  url:			https://twitter.com/andre_scutieri

gems: ['jekyll-paginate']

paginate:			2

copyright-year: 2016
version:			2.0.0

